Feature/RF-27 Direction
STih07/upmefrontend pull request #37
Opened 2020-08-18 18:43 UTC by Paxton1337

Layout

2020-09-11 05:49 UTC, STih07 requested changes

2020-09-11 05:49 UTC, STih07 commented on src/app/modules/directions/components/directions/directions.component.html
> +                                <a class="link" target="_blank" href="#!"><span class="link">https://www.linkedin.com/in/alex-zabiako-b696a090...</span></a>
нормальную ссылку

2020-09-11 05:49 UTC, STih07 commented on src/app/modules/directions/components/directions/directions.component.html
> +                        <button class="btn font-weight-light py-1 btn-secondary btn-filter-width text-sm">Всего: 68</button>
Модель (тут и ниже)

2020-09-11 05:49 UTC, STih07 commented on src/app/modules/directions/components/directions/directions.component.html
> +                                            <small class="d-block text-dark color-black custom-fs-12 font-weight-900">#0{{user.id}}</small>
0 это часть id. Или у нас 0103, 02222?

2020-09-11 05:49 UTC, STih07 commented on src/app/modules/directions/components/directions/directions.component.html
> +                                            <small class="d-block text-dark color-black custom-fs-12 font-weight-900">#0{{user.id}}</small>
Можно уточнить правильное ожидаемое поведение у дизайнеров

2020-09-11 05:49 UTC, STih07 commented on src/app/modules/directions/components/directions/directions.component.html
> +                                        <span class="ml-3 text-sm">Отлично</span>
Модель

2020-09-11 05:49 UTC, STih07 commented on src/app/modules/directions/pipe/status-task.pipe.ts
> +        if (status === DirectionTaskStatus.AWAIT) {
Есть смысл подумать о свитчкейсах для лучшей читабельности

2020-09-11 13:38 UTC, Paxton1337 commented on src/app/modules/directions/components/directions/directions.component.html
> +                                            <small class="d-block text-dark color-black custom-fs-12 font-weight-900">#0{{user.id}}</small>
думаю стоит уточнить и сделать pipe для чисел меньше 10 делать 01,02...

2020-09-13 11:03 UTC, STih07 approved these changes

2020-09-13 11:03 UTC, merged