RF-46 Add EditProfile modal
STih07/upmefrontend pull request #44
Opened 2020-09-09 15:25 UTC by ArtyomKazlanzhi

2020-09-09 19:37 UTC, Paxton1337 requested changes
Передавай эстафету Сереге)

2020-09-09 19:37 UTC, Paxton1337 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.html
> +    <label for="name" class="text-dark custom-fs-14">Полное имя</label>
Все custom-fs-14 заменить на text-sm

2020-09-09 19:37 UTC, Paxton1337 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.html
> +      <img alt="Image placeholder" src="assets/img/edit-profile-modal.png" class="img-edit-profile">
Скорей всего мы подгружаем фотку пользователя, соответственно будет фотка такая же как в этом
![image](https://user-images.githubusercontent.com/60095300/92638725-64bfa280-f2e3-11ea-8344-56344aeda32a.png)
Это не наезд, просто не надо добавлять лишних картиночек, так что все вроде ок

2020-09-09 19:37 UTC, Paxton1337 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.html
> +    <button type="button" class="btn btn-primary btn-sm py-2 custom-fs-14" [disabled]="editProfileForm.invalid" (click)="onCancel()">Сохранить</button>
Надо обговорить с Серегой метод для подтверждения, ибо он будет передавать форму, по идее должен быть отдельный метод который так же закрывает модалку, но в качестве параметра передает форму

2020-09-09 19:37 UTC, Paxton1337 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.scss
> +.custom-edit-modal {
Шо это, а главное зачем (он нигде не юзается в шаблоне) Удоли

2020-09-09 19:37 UTC, Paxton1337 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.scss
> +label {
Вот тут приколюха, мы сделаем так, я не могу сказать насколько круто трогать все лейблы, но наверное лучше будет удалить это и добавить в лебах класс "mt-2 mb-0"

2020-09-09 19:37 UTC, Paxton1337 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.scss
> +  padding: 8px 14px;
А где используется это?) Улолить

2020-09-09 19:37 UTC, Paxton1337 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.scss
> +.p-rank {
Удалить на месте него поставить класс text-primary

2020-09-09 19:37 UTC, Paxton1337 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.spec.ts
> +
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

2020-09-09 19:37 UTC, Paxton1337 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.spec.ts
> +      declarations: [ EditProfileModalComponent ]
Добавить providers: [NgbActiveModal]

2020-09-10 07:32 UTC, ArtyomKazlanzhi commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.html
> +      <img alt="Image placeholder" src="assets/img/edit-profile-modal.png" class="img-edit-profile">
Давай лучше заменим фотку этого человека на Ани)

2020-09-10 07:34 UTC, ArtyomKazlanzhi commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.html
> +    <button type="button" class="btn btn-primary btn-sm py-2 custom-fs-14" [disabled]="editProfileForm.invalid" (click)="onCancel()">Сохранить</button>
Там по любому будет какой-то PUT/PATCH запрос на сервер, чтобы проапдейтить инфу, предлагаю пока закрывать модалку, как появится ендпоинт, то сделаем таску на submit кнопку

2020-09-10 07:44 UTC, Paxton1337 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.html
> +    <button type="button" class="btn btn-primary btn-sm py-2 custom-fs-14" [disabled]="editProfileForm.invalid" (click)="onCancel()">Сохранить</button>
Согласен, как таковых у меня нет претензий, просто это на будущее

2020-09-10 07:44 UTC, STih07 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.html
> +      <img alt="Image placeholder" src="assets/img/edit-profile-modal.png" class="img-edit-profile">
Момент несущественный, потом будет заменяться на ответ с сервера

2020-09-10 07:46 UTC, STih07 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.scss
> +label {
Это была моя идея быстрого фикса, в целом да, лучше воспользоваться классами бутстрапа

2020-09-10 07:48 UTC, STih07 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.scss
> +label {
Также просьба сопоставить цвет #3c4858 и если он уже есть в теме, использовать существующие классы для цветов (text-muted, text-primary, text-secondary, ...)

2020-09-10 07:55 UTC, STih07 commented on src/app/modals/edit-profile-modal/edit-profile-modal.component.scss
> +::placeholder {
Лучше подвязывать ::placeholder к конкретному инпуту, например, по классу
Или хотя бы  `input::placeholder`

2020-09-10 07:56 UTC, STih07 approved these changes

2020-09-10 13:57 UTC, Paxton1337 approved these changes

2020-09-10 13:57 UTC, merged