feature/RF-52 Implement errors validation on Login form
STih07/upmefrontend pull request #52
Opened 2020-09-21 15:32 UTC by ArtyomKazlanzhi

2020-09-23 15:00 UTC, STih07 commented on src/app/modules/auth/components/login/login.component.html
> +                      <span [class]="singInForm.controls.email.errors?.noSuchEmail ? 'visible' : 'invisible'" class="mb-0 text-danger text-sm">Нет пользователя с таким Email</span>
Зачем два класса? Почему не сделать [class.invisible]="!singInForm.controls.email.errors?.noSuchEmail" или наоборот?

2020-09-23 15:00 UTC, STih07 commented on src/app/modules/auth/components/login/login.component.html
> +                      <span [class]="singInForm.controls.password.errors?.wrongPassword ? 'visible' : 'invisible'" class="mb-0 text-danger text-sm">Пароль неверный</span>
Аналогично предыдущему замечанию

2020-09-23 15:02 UTC, STih07 commented on src/app/modules/auth/services/auth.service.ts
> +  private static BASE_URL = 'https://murmuring-stream-64302.herokuapp.com/api/auth';
Зачем static? Вынести API_URL в environment.ts, здесь можно просто добавить к нему 'api/auth'

2020-09-23 15:04 UTC, STih07 commented on src/app/modules/profile/services/fake-http.service.ts
>      return this.http.get(`https://murmuring-stream-64302.herokuapp.com/api/profile/${id}`, {headers}).pipe(
Аналогично про API_URL

2020-09-23 15:05 UTC, STih07 requested changes
Needs changes

2020-09-28 12:35 UTC, ArtyomKazlanzhi commented on src/app/modules/auth/components/login/login.component.html
> +                      <span [class]="singInForm.controls.email.errors?.noSuchEmail ? 'visible' : 'invisible'" class="mb-0 text-danger text-sm">Нет пользователя с таким Email</span>
Вот так? @STih07 
`<span [class.invisible]="!singInForm.controls.email.errors?.noSuchEmail" class="mb-0 text-danger text-sm">Нет пользователя с таким Email</span>`

2020-09-29 15:11 UTC, STih07 approved these changes

2020-09-29 15:11 UTC, merged